name: Tests and release

on:
  push:
    branches:
      - "**"
  pull_request:

env:
  CRATE_NAME: liveness-check
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1

jobs:
  test:
    name: ${{ matrix.platform.os-name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            bin: liveness-check
            name: precious-Linux-x86_64-musl.tar.gz
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - name: Install musl and OpenSSL for target
        run: |
          sudo apt-get update
          sudo apt-get install -y musl musl-dev musl-tools
          curl -O https://www.musl.cc/x86_64-linux-musl-cross.tgz
          tar -xvf x86_64-linux-musl-cross.tgz
          export PATH=$PATH:$(pwd)/x86_64-linux-musl-cross/bin
          export OPENSSL_DIR=/usr
          export PKG_CONFIG_SYSROOT_DIR=/usr
          export PKG_CONFIG_PATH=/usr/lib/pkgconfig

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
          strip: true
          cross-version: 4090beca3cfffa44371a5bba524de3a578aa46c3
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: liveness-check
          target: ${{ matrix.platform.target }}
        if: matrix.toolchain == 'stable'
